### ISSUE TITLE
Attempting to parse byte string results in panic

### ISSUE THREAD

**Issue by frewsxcv** [bytecodealliance/wasmparser#21]
Attempting read `b"\x00asm\x01\x00\x00\x00"` into the `Parser` results in a panic: `'Parser in end state'`. Not sure if this library is ready to be fuzzed at this point, but I found this bug via [cargo-fuzz](https://github.com/rust-fuzz/cargo-fuzz). You can try fuzzing by checking out [this branch](https://github.com/yurydelendik/wasmparser.rs/compare/master...frewsxcv:fuzz?expand=1), running `cargo install cargo-fuzz`, and running `cargo fuzz run fuzz_target_1`.

**Comment by yurydelendik** [comment]
The [fuzz loop](https://github.com/yurydelendik/wasmparser.rs/compare/master...frewsxcv:fuzz?expand=1#diff-f27b6cbe9503376c022f6461bb962f88R8) is missing EndWasm state:

```
    loop {
        match *parser.read() {
            wasmparser::ParserState::Error(..) => break,
            wasmparser::ParserState::EndWasm => break,
            _ => (),
        }
    }
```

`Error` and `EndWasm` are two terminal states.

**Comment by yurydelendik** [comment]
> Not sure if this library is ready to be fuzzed at this point

It's ready to be fuzzed.

**Comment by frewsxcv** [comment]
Updated the branch to `break` on `EndWasm` too. Here's a new issue:

`b"\x00asm\x01\x00\x00\x00\x05\x05\x01\x00ms\x00\x00\x05\x05\x01\x01\x01\x80\x02\x01\x01\x01\x80\x02"`

```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', src/parser.rs:606
note: Run with `RUST_BACKTRACE=1` for a backtrace.
==14701== ERROR: libFuzzer: deadly signal
    #0 0x10b94c500 in __sanitizer_print_stack_trace (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x62500)
    #1 0x10a5113fb in fuzzer::Fuzzer::CrashCallback() (fuzz_target_1:x86_64+0x1000333fb)
    #2 0x10a5113ad in fuzzer::Fuzzer::StaticCrashSignalCallback() (fuzz_target_1:x86_64+0x1000333ad)
    #3 0x10a55f0a7 in fuzzer::CrashHandler(int, __siginfo*, void*) (fuzz_target_1:x86_64+0x1000810a7)
    #4 0x7fffbe4afb39 in _sigtramp (libsystem_platform.dylib:x86_64+0x2b39)
    #5 0x1168c086c  (<unknown module>)
    #6 0x7fffbe33441f in abort (libsystem_c.dylib:x86_64+0x5f41f)
    #7 0x10a611468 in __rust_start_panic (fuzz_target_1:x86_64+0x100133468)
    #8 0x10a6101dc in rust_panic (fuzz_target_1:x86_64+0x1001321dc)
    #9 0x10a610193 in std::panicking::rust_panic_with_hook::h8b9b25777425677b (fuzz_target_1:x86_64+0x100132193)
    #10 0x10a60ff84 in std::panicking::begin_panic::h69fe06a9d67b6165 (fuzz_target_1:x86_64+0x100131f84)
    #11 0x10a60fef2 in std::panicking::begin_panic_fmt::haf8695bfb6c52436 (fuzz_target_1:x86_64+0x100131ef2)
    #12 0x10a60fe57 in rust_begin_unwind (fuzz_target_1:x86_64+0x100131e57)
    #13 0x10a611970 in core::panicking::panic_fmt::hfedd6515bcee8bb1 (fuzz_target_1:x86_64+0x100133970)
    #14 0x10a611874 in core::panicking::panic::hd25e89dc434847c1 (fuzz_target_1:x86_64+0x100133874)
    #15 0x10a5a63ce in wasmparser::parser::BinaryReader::read_bytes_till::h1203ebbed1d15842 (fuzz_target_1:x86_64+0x1000c83ce)
    #16 0x10a5eace0 in wasmparser::parser::Parser::read_section_body_bytes::ha1c5acae5290d3e5 (fuzz_target_1:x86_64+0x10010cce0)
    #17 0x10a5e4f73 in wasmparser::parser::Parser::read_section_body::he4788e77878ab6dd (fuzz_target_1:x86_64+0x100106f73)
    #18 0x10a5ebf94 in wasmparser::parser::Parser::read_wrapped::hc9ac1624de9ce9de (fuzz_target_1:x86_64+0x10010df94)
    #19 0x10a5f0a86 in wasmparser::parser::Parser::read::h3efa064c93f3fcaf (fuzz_target_1:x86_64+0x100112a86)
    #20 0x10a4e5718 in rust_fuzzer_test_input (fuzz_target_1:x86_64+0x100007718)
    #21 0x10a4e9521 in libfuzzer_sys::test_input_wrap::_$u7b$$u7b$closure$u7d$$u7d$::h7d25ba79ba6008d5 (fuzz_target_1:x86_64+0x10000b521)
    #22 0x10a4e754e in std::panicking::try::do_call::he4ca3e300fd7dda0 (fuzz_target_1:x86_64+0x10000954e)
    #23 0x10a61145b in __rust_maybe_catch_panic (fuzz_target_1:x86_64+0x10013345b)
    #24 0x10a4e6bb4 in std::panicking::try::hd64eaa34fcd4c52a (fuzz_target_1:x86_64+0x100008bb4)
    #25 0x10a4e663c in std::panic::catch_unwind::hf86a03ca8ac2752e (fuzz_target_1:x86_64+0x10000863c)
    #26 0x10a4e908c in LLVMFuzzerTestOneInput (fuzz_target_1:x86_64+0x10000b08c)
    #27 0x10a5148ff in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (fuzz_target_1:x86_64+0x1000368ff)
    #28 0x10a514cfd in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long) (fuzz_target_1:x86_64+0x100036cfd)
    #29 0x10a51802d in fuzzer::Fuzzer::MutateAndTestOne() (fuzz_target_1:x86_64+0x10003a02d)
    #30 0x10a518a73 in fuzzer::Fuzzer::Loop() (fuzz_target_1:x86_64+0x10003aa73)
    #31 0x10a4f27cc in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (fuzz_target_1:x86_64+0x1000147cc)
    #32 0x10a52431f in main (fuzz_target_1:x86_64+0x10004631f)
    #33 0x7fffbe2a0234 in start (libdyld.dylib:x86_64+0x5234)
```

EDIT: also added a trophy ;) https://github.com/rust-fuzz/trophy-case/blob/master/README.md

**Comment by yurydelendik** [comment]
Thank you
